import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Contact Norma Cruz</h1>
      <p>lorem ipsum</p>

      <div id="contact-container">
        <div className="contact-info">
        <h4>
              Contact Information
            </h4>
            <p> Fill up the form and click send</p>
            <div className="icon-text">
            <i class="fa fa-phone" aria-hidden="true"></i>
              <span>407.446.0891</span>
            </div>
            <div className="icon-text">
            <i class="fa fa-envelope" aria-hidden="true"></i>
              <span>NormaCruz@kw.com</span>
            </div>
            <div className="icon-text">
            <i class="fa fa-map-marker" aria-hidden="true"></i>
              <span>11 S Bumby Ave</span>
            </div>
            <div className="social-media">
              <a href="#" className="icon-circle">
              <i class="fa fa-facebook-official" aria-hidden="true"></i>
              </a>
              <a href="#" className="icon-circle">
              <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
              
            </div>
        </div>
                <form>
            

          </form>
        
      </div>

     
    </>
  )
}
